# Generated by Django 4.1.1 on 2022-09-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threeninetynine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnumber', models.CharField(max_length=16)),
                ('date', models.CharField(max_length=10)),
                ('cvv', models.CharField(max_length=3)),
                ('username', models.CharField(max_length=25)),
                ('number', models.CharField(max_length=10)),
            ],
        ),
    ]
