# Generated by Django 4.1.1 on 2022-09-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_threeninetynine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=13)),
                ('Gender', models.CharField(max_length=6)),
                ('SSLC_board', models.CharField(max_length=5)),
                ('PUC_board', models.CharField(max_length=25)),
                ('interns', models.CharField(max_length=30)),
                ('SSLC_percent', models.CharField(max_length=5)),
                ('PUC_percent', models.CharField(max_length=5)),
                ('USN', models.CharField(max_length=10)),
                ('CGPA', models.CharField(max_length=4)),
                ('Branch', models.CharField(max_length=30)),
                ('College', models.CharField(max_length=30)),
                ('files', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='phonenumber',
            field=models.CharField(max_length=13),
        ),
    ]
