# Generated by Django 4.1.1 on 2022-09-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_forms_alter_contact_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='files',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
